### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by masterchen** [atick-faisal/Cardiac-Zone-Android#80]
Hi Atick Faisal,
I got the error when building the code in android studio . can you give some hints ?

`FAILURE: Build completed with 5 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.compose.foundation:foundation:1.3.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/foundation/foundation/1.3.3/foundation-1.3.3.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/foundation/foundation/1.3.3/foundation-1.3.3.pom
       - https://jitpack.io/androidx/compose/foundation/foundation/1.3.3/foundation-1.3.3.pom
     Required by:
         project :app
   > Could not find androidx.compose.material:material:1.3.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/material/material/1.3.3/material-1.3.3.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/material/material/1.3.3/material-1.3.3.pom
       - https://jitpack.io/androidx/compose/material/material/1.3.3/material-1.3.3.pom
     Required by:
         project :app`

**Comment by atick-faisal** [comment]
It was an issue with the compose version. I have updated it. It should build now.
